### ISSUE TITLE
HTTP Error 304: Not Modified

### ISSUE THREAD

**Issue by schumi2004** [cflannagan/service.subtitles.addic7ed#10]
Since today i'm getting this error.
Any idea?

20:50:27 T:139810504075008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 304: Not Modified
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/service.subtitles.addic7ed/service.py", line 269, in <module>
                                                Search(item)
                                              File "/storage/.xbmc/addons/service.subtitles.addic7ed/service.py", line 167, in Search
                                                query_TvShow(item['tvshow'], item['season'], item['episode'], item['3let_language'], filename)
                                              File "/storage/.xbmc/addons/service.subtitles.addic7ed/service.py", line 69, in query_TvShow
                                                query(searchurl, langs, file_original_path, filename_string)
                                              File "/storage/.xbmc/addons/service.subtitles.addic7ed/service.py", line 82, in query
                                                page = urllib2.build_opener().open(request)
                                              File "/home/ubuntu/github/OpenELEC.tv/build.OpenELEC-Generic.x86_64-devel/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 406, in open
                                              File "/home/ubuntu/github/OpenELEC.tv/build.OpenELEC-Generic.x86_64-devel/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 519, in http_response
                                              File "/home/ubuntu/github/OpenELEC.tv/build.OpenELEC-Generic.x86_64-devel/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 444, in error
                                              File "/home/ubuntu/github/OpenELEC.tv/build.OpenELEC-Generic.x86_64-devel/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
                                              File "/home/ubuntu/github/OpenELEC.tv/build.OpenELEC-Generic.x86_64-devel/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
                                            HTTPError: HTTP Error 304: Not Modified
                                            -->End of Python script error report<--
20:50:28 T:139810520770304   ERROR: GetDirectory - Error getting plugin://service.subtitles.addic7ed/?action=search&languages=Dutch

**Comment by Borromini** [comment]
Same here.

**Comment by schumi2004** [comment]
Changed to this fork but getting an error https://github.com/Mafarricos/service.subtitles.addic7ed

23:00:05 T:139722046977792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name '**cwd**' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/service.subtitles.addic7ed/service.py", line 260, in <module>
                                                Search(item)
                                              File "/storage/.xbmc/addons/service.subtitles.addic7ed/service.py", line 167, in Search
                                                query_TvShow(item['tvshow'], item['season'], item['episode'], item['3let_language'], filename)
                                              File "/storage/.xbmc/addons/service.subtitles.addic7ed/service.py", line 66, in query_TvShow
                                                name = addic7ize(name).lower().replace(" ", "_")
                                              File "/storage/.xbmc/addons/service.subtitles.addic7ed/resources/lib/Addic7edUtilities.py", line 73, in addic7ize
                                                addic7ize_dict = eval(open(__cwd__ + '/addic7ed_dict.txt').read())
                                            NameError: global name '**cwd**' is not defined
                                            -->End of Python script error report<--

A quick fix is adding

```
  "__cwd__        = xbmc.translatePath( __addon__.getAddonInfo('path') ).decode("utf-8")"
```

to  Addic7edUtilities.py (without quotes)

**Comment by cflannagan** [comment]
Is it still happening with my fork? Wondering if this was a momentary thing or if it has became permanent? Thanks!

**Comment by schumi2004** [comment]
@cflannagan the issue with your repo is the 304 error and is still there as off today.

**Comment by cflannagan** [comment]
Which show were you trying to obtain the subtitles for? I'm trying to reproduce this.

**Comment by schumi2004** [comment]
The last time i tried it extensively it was for almost every show, Suits, Arrow, Sleepy Hollow, Nikita
Will give it a run tonight when i have some spare time.

**Comment by schumi2004** [comment]
The issue is still there, addon is useless for now.

**Comment by schumi2004** [comment]
I think i found the issue.
For some reason a temp folder was created in service.subtitles.addic7ed in addon_data folder with a addi7ed.srt file in it.
Deleting this folder solved the error.

**Comment by schumi2004** [comment]
Seems error returned but my previous solution isn't working now.

**Comment by delcara** [comment]
Same issue here, with every tv-show.

**Comment by Amelandbor** [comment]
Think I have the solution for this one. a82bb842d85f125e056ff2db599063bf2a55d13d

**Comment by thombet** [comment]
Your solution solves it for me @Amelandbor ! Thanks !
Could you create a pull request?

**Comment by Amelandbor** [comment]
I don't think this repository is being updated anymore, so I will keep it with my own fork. Also I have the dictionary in a separate text file so it's easier for users to edit.

**Comment by cflannagan** [comment]
@Amelandbor 

Yup - my priorities has changed recently and I have to admit defeat - I don't think I can maintain this repository in any meaningful manner for a while. 

Would you be willing to have me add a note into my repo's README.md saying you are now maintaining the project, and that I am no longer maintaining? Want to ensure people seeking out the great plugin can go quickly to the correct place. Let me know

**Comment by Amelandbor** [comment]
@cflannagan 

I'm fine with that, not very good in python, but will see what I can do.
Thanks for the work you've done.
